github_user: "fer-correa"
organization: "todogroup" # Leave empty or remove
repositories:
  - "todogroup/ospology"
  - "todogroup/governance"
  - "innersourcecommons/InnerSourcePatterns"
  - "innersourcecommons/InnerSourceLearningPath"
